VTK: Add zSpace VTK module
VTK-specific classes of the zSpace plugin had been moved to a dedicated zSpace module.
This bump allows the remaining classes in the plugin to use them.

* Thomas Galland: 'zSpaceVTKIntegration'
  * 27ad5ad6d2 Add CI exception - zSpace
  * 4eabb78452 Add the VTK zSpace module
  * Merge-request: https://gitlab.kitware.com/vtk/vtk/merge_requests/9602
* Spiros Tsalikis: 'fix explicit structured grid deep copy'
  * 3baca77384 Test vtkExplicitStructuredGrid::DeepCopy
  * 1221e4f3cb vtkExplicitStructuredGrid: Fix DeepCopy
  * Merge-request: https://gitlab.kitware.com/vtk/vtk/merge_requests/9831
* Ben Boeckel: 'testing python deprecation'
  * 10e10ffc12 vtkModuleTesting: fail Python tests on deprecation warnings
  * e648a62857 unittest: replace deprecated `failUnlessEqual` calls
  * Merge-request: https://gitlab.kitware.com/vtk/vtk/merge_requests/9834
* Ben Boeckel: 'ci osmesa wheels'
  * 6f3f8b2956 ci: update test exclusions to cover OSMesa wheel testing too
  * 3a78f59d6e Documentation: add release note for OSMesa wheels
  * 693b445dec vtkMatplotlibMathTextUtilities: guard deletion of `Interpreter`
  * 815fca07ea gitlab-ci: require testing to succeed for wheel uploads
  * c84cbfb107 Merge branch 'ci-osmesa-wheels-release' into ci-osmesa-wheels
  * c7cdc16288 gitlab-ci: add jobs for OSMesa wheels
  * bb2a80001b ci: support alternative wheel names in SDK archives
  * 87fed91890 ci: add a script to extract the OSMesa build
  * ...
  * Merge-request: https://gitlab.kitware.com/vtk/vtk/merge_requests/9820
* Yohann Bearzi: 'threaded writer opti'
  * a5be29f7d2 vtkThreadedCallbackQueue: adding a .md file
  * b966f916b8 vtkThreadedCallbackQueue: encapsulating the thread worker
  * 78c090c001 vtkThreadedCallbackQueue: renaming Worker to Invoker
  * 0c4cdaf13e vtkThreadedCallbackQueue: changing SetNumberOfThreads behavior
  * Merge-request: https://gitlab.kitware.com/vtk/vtk/merge_requests/9825
* Ben Boeckel: 'rendering tk dead code removal'
  * cf4a98912b Rendering/Tk: use `nullptr` in some more places
  * 97cf16c8dc Rendering/Tk: remove VTK_PYTHON_BUILD symbol
  * Merge-request: https://gitlab.kitware.com/vtk/vtk/merge_requests/9829
* Ben Boeckel: 'banesullivan master patch 29335'
  * 1a74caafa5 Add VTK_VERSION_SUFFIX and VTK_DIST_NAME_SUFFIX for wheel name modification
  * Merge-request: https://gitlab.kitware.com/vtk/vtk/merge_requests/9674
* Mathieu Westphal: 'fix objreader segfault'
  * 4b7d53504b vtkOBJReader: avoid a possible null buffer access
  * Merge-request: https://gitlab.kitware.com/vtk/vtk/merge_requests/9827
* David Gobbi: 'temp'
  * f976ccba89 Fix Rendering clang tidy warnings
  * feaf54ce89 Fix RenderingTk inclusion of .cxx files
  * 31065669ce Perform a render when vtkTkRenderWidget is shrunk
  * edea14e455 Change search path for vtkRenderingTk library
  * c33cd5317d Enable VTK_USE_TK in linux testing
  * 06f6fc0196 Remove obsolete FindTCL.cmake in favor of CMake's
  * 3f944e5972 Fix RenderingTk compilation
  * Merge-request: https://gitlab.kitware.com/vtk/vtk/merge_requests/9819
* Ben Boeckel: 'ci openxr runtime package'
  * e3d7eaec6c gitlab-ci: use new CI image with OpenXR runtime
  * c90f533659 ci: add `openxr` runtime package to the CI image
  * Merge-request: https://gitlab.kitware.com/vtk/vtk/merge_requests/9824
* David Gobbi: 'wrapper sprintf bufsize'
  * 8758f07686 Fix snprintf buffer size in vtkParseHierarchy
  * Merge-request: https://gitlab.kitware.com/vtk/vtk/merge_requests/9826
* Christos Tsolakis: 'import abort openturns'
  * 90b47852ed Add abort to OpenTURNS filters
  * Merge-request: https://gitlab.kitware.com/vtk/vtk/merge_requests/9778
* Christos Tsolakis: 'import abort modeling'
  * 770fd3d1e9 Add abort to SMP filters
  * 0d3efb08ba Add abort to Modeling filters
  * Merge-request: https://gitlab.kitware.com/vtk/vtk/merge_requests/9777
* Yohann Bearzi: 'threaded writer'
  * 1bca529f36 vtkThreadedCallbackQueue: new utility
  * Merge-request: https://gitlab.kitware.com/vtk/vtk/merge_requests/9804
* Ben Boeckel: 'docker updates'
  * 4b4ab81bb3 gitlab-ci: use new CI image
  * 8ebf46ae66 Add tkinter, tcl-devel, tk-devel to Dockerfile
  * d8d7d128de ci: Add openxr on fedora docker
  * Merge-request: https://gitlab.kitware.com/vtk/vtk/merge_requests/9823
* David Gobbi: 'deprecate no x resize'
  * 02a28a4aae Deprecate vtkXOpenGLRenderWindow::SetSizeNoXResize
  * Merge-request: https://gitlab.kitware.com/vtk/vtk/merge_requests/9815
* Mathieu Westphal: 'fix compute bounds compilation error'
  * 5f701e9529 vtkBoundingBox: Add ComputeBounds with all id types
  * Merge-request: https://gitlab.kitware.com/vtk/vtk/merge_requests/9794
* Ben Boeckel: 'minor fixups'
  * d5bf873b80 vtkSMPSelection: wrap error message
  * 7ed7fdf631 new-release: sync with reality
  * Merge-request: https://gitlab.kitware.com/vtk/vtk/merge_requests/9816
* David Gobbi: 'fix no x resize'
  * 215c1b552f Fix accidental breakage of interactive X resizing
  * Merge-request: https://gitlab.kitware.com/vtk/vtk/merge_requests/9813
* David Gobbi: 'patch/web import'
  * 95efe3df63 Add vtkmodules/web/errors.py
  * Merge-request: https://gitlab.kitware.com/vtk/vtk/merge_requests/9814
* Mathieu Westphal: 'hide using warning'
  * 0f4d936f43 Fix XR/VR related warnings
  * Merge-request: https://gitlab.kitware.com/vtk/vtk/merge_requests/9757
* Ben Boeckel: 'update to v9.2.3'
  * d328c31ec8 release: clarify Python 3.11 support note
  * c52bb7fb56 release: note that 9.2.3 added some bits
  * de1181c510 release: wrap long lines
  * Merge-request: https://gitlab.kitware.com/vtk/vtk/merge_requests/9808
* Ben Boeckel: 'cdash https'
  * 1364e8465b Change CTEST_DROP_METHOD from http to https
  * Merge-request: https://gitlab.kitware.com/vtk/vtk/merge_requests/9802
* Ben Boeckel: 'web extra deps'
  * e81740d16d Web/Python: handle missing dependencies gracefully
  * e1e494deb9 Wep/Python: move Python dependencies to extras_require
  * Merge-request: https://gitlab.kitware.com/vtk/vtk/merge_requests/9727
* Ben Boeckel: 'update vtk xdmf2 hdf5'
  * e81a2fecc8 Workaround using 1.13.1 in provided hdf5
  * 8701b90c78 Xdmf2: Update HDF5 driver for 1.13.2
  * Merge-request: https://gitlab.kitware.com/vtk/vtk/merge_requests/9690
* Julien Fausty: 'fix rdp strategy'
  * 69a92b754b fix iterator manipulation in vtkToImplicitRamerDouglasPeuckerStrategy
  * Merge-request: https://gitlab.kitware.com/vtk/vtk/merge_requests/9800
* Timothee Chabat: 'fix output table fft'
  * 3801771a87 vtkTableFFT: drop columns instead of squeeze them
  * Merge-request: https://gitlab.kitware.com/vtk/vtk/merge_requests/9772
* Ben Boeckel: 'test python 3.11 on windows'
  * 1fd7e6f087 ci: update Python requirements
  * 9f1507555c ci: use Python 3.11 on Windows
  * Merge-request: https://gitlab.kitware.com/vtk/vtk/merge_requests/9593
* Ben Boeckel: 'ci arch tags'
  * 7ae3b4f132 Merge branch 'ci-arch-tags-release' into ci-arch-tags
  * 9b2769b96d gitlab-ci: remove `linux-3.17` tag
  * b4b1fa9866 gitlab-ci: use arch-specific tags for OS selection
  * Merge-request: https://gitlab.kitware.com/vtk/vtk/merge_requests/9789
* Ben Boeckel: 'fix build vtkSMPToolsImpl'
  * 37c533b9a5 vtkSMPToolsImpl: Remove second constructor
  * Merge-request: https://gitlab.kitware.com/vtk/vtk/merge_requests/9793
* Ben Boeckel: 'numpy deprecations under mpi'
  * 66fdb9f0c3 numpy: avoid `numpy.bool` in MPI-using code
  * Merge-request: https://gitlab.kitware.com/vtk/vtk/merge_requests/9795
* Ben Boeckel: 'standalone wheel testing'
  * d32a3cc054 gitlab-ci: test built wheels using VTK's test suite
  * bf483be81c gitlab-ci: activate the wheel testing venv
  * b59f60b25f Testing/ExternalWheel: add a project to test a VTK wheel
  * 569f55d656 vtkModuleTesting: conditionalize the `--enable-bt` argument
  * 1713f8cc45 cmake: mask Cxx testing directories if only testing Python
  * a847b63277 ci: remove trailing whitespace
  * 006ed6022d ci: add 3.11 jobs to the expected job group
  * Merge-request: https://gitlab.kitware.com/vtk/vtk/merge_requests/9765
* Julien Fausty: 'fix rdp strategy'
  * 2c5866b2ec fix RDP strategy by not referencing an end iterator
  * Merge-request: https://gitlab.kitware.com/vtk/vtk/merge_requests/9790
* David Gobbi: 'transform axis epsilon'
  * 9548dcf373 Adjust VTK_AXIS_EPSILON for GetOrientation
  * Merge-request: https://gitlab.kitware.com/vtk/vtk/merge_requests/9769
* Ben Boeckel: 'fix gcc 4.8 5 compilation'
  * f7c4049b4c Fix: error: array must be initialized with a brace-enclosed initializer
  * 067cc56fba vtkAppendSelection: use vtksys::RegularExpression instead of regex
  * 9f516058c2 Fix: error: define (copy)constructor
  * Merge-request: https://gitlab.kitware.com/vtk/vtk/merge_requests/9728
* Ben Boeckel: 'patch/ren win serializers'
  * a90a89da9e Update Web render window serializers and remove print statements
  * Merge-request: https://gitlab.kitware.com/vtk/vtk/merge_requests/9766
* Ben Boeckel: 'numpy test deprecation'
  * ce55bf0376 Merge branch 'numpy-test-deprecation-release' into numpy-test-deprecation
  * 2a38264a55 Merge branch 'numpy-test-deprecation-release' into numpy-test-deprecation
  * 9f7d059ec6 Testing: ignore 9.1.0 deprecation warnings
  * db81ed74ad TestGeometryFilter: ignore 9.2.0 deprecation warnings
  * 666c0ad79e TestHyperTreeGrid3DCursorsMandel: use non-deprecated getter
  * a271889311 testing: avoid usage of deprecated `unittest` methods
  * 1439f780f3 TestNumpyInterface: use non-deprecated `numpy.<type>` replacements
  * Merge-request: https://gitlab.kitware.com/vtk/vtk/merge_requests/9788
* Ben Boeckel: 'wrapping tools leaks'
  * b840ef1d8c vtkParse: fix leak with template template cases
  * a0c93fda33 vtkWrapPythonOverload: free `std::vector` template arguments
  * 050ec4eb23 vtkParsePreprocess: add included file to the cache
  * 2e5ed3232b vtkParseMerge: free the functions array if none are left after merging
  * cb24fdeb27 Wrapping/Tools: Fix method signature leak in vtkWrapPython
  * 7f40f8cb6e Wrapping/Tools: Fix argument string leaks in wrapper tools
  * 33693064fa Wrapping/Tools: Fix memory hinfo leak in vtkWrapPython, vtkWrapJava
  * ad12e71dbe vtkParse: fix misparse and leak for type alias
  * ...
  * Merge-request: https://gitlab.kitware.com/vtk/vtk/merge_requests/9773
* Ben Boeckel: 'vtk component limits'
  * 1805eae33b vtk-config: handle non-VTK components
  * c1f683627f vtk-config: complete the list of non-module components
  * Merge-request: https://gitlab.kitware.com/vtk/vtk/merge_requests/8677
* Ben Boeckel: 'vtkModulePython custom interpreter'
  * a43395161a gitlab-ci: add an extra `PATH` entry to let `.pyi` work
  * 7ca814dcf8 cmake: disable the interpreter in known-bad scenarios
  * ecb23a922f vtkModuleWrapPython: support passing in an interpreter
  * 3ffde1cf20 vtkModuleWrapPython: wrap variable expansion in quotes
  * Merge-request: https://gitlab.kitware.com/vtk/vtk/merge_requests/9076
* Mathieu Westphal: 'update review doc'
  * 9ddeba715d Update review doc
  * Merge-request: https://gitlab.kitware.com/vtk/vtk/merge_requests/9774
* Mathieu Westphal: 'improve pbr textures'
  * a56d0352f9 Improve PBR textures
  * Merge-request: https://gitlab.kitware.com/vtk/vtk/merge_requests/9767