vtkPlotlyJsonExporter: resolve ambiguous call setting nlohmann::json value
On the Intel oneAPI 2021 compilers, this call was leading to compilation
error due to an ambiguous call to __is_path_src:

bits/fs_path.h:119:16: error: call to '__is_path_src' is ambiguous

    : decltype(__is_path_src(std::declval<_Source>(), 0))

Resolved by statically casting the vtkStdString returned by
chart->GetTitle() to a std::string.